image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  policy: pull
  paths:
    - .cache/pip
    - venv/
  key:
    files:
      - setup.cfg
      - requirements.test.txt

stages:
  - linting
  - tests

requirements install:
  stage: .pre
  cache:
    policy: pull-push
    paths:
      - .cache/pip
      - venv/
    key:
      files:
        - setup.cfg
        - requirements.test.txt
  rules:
    - changes:
      - setup.cfg
      - requirements.test.txt
  script:
    - python --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.test.txt

formatting:
  stage: linting
  before_script:
    - source venv/bin/activate
  script:
    - codespell
    - black --safe --check .
    - isort -c ./custom_components/

code quality:
  stage: linting
  before_script:
    - source venv/bin/activate
  script:
    - flake8
    - pylint ./custom_components/purpleair/
    - mypy ./custom_components/purpleair/
